---
- hosts: openstack
  any_errors_fatal: true
  roles:
    - role: openstack
      become: true
  vars:
    https_proxy: http://8.8.8.8:88/
    no_proxy: 10.0.0.0/16,192.168.122.0/24
  environment:
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    OS_PROJECT_DOMAIN_NAME: "default"
    OS_USER_DOMAIN_NAME: "default"
    OS_PROJECT_NAME: "admin"
    OS_USERNAME: "admin"
    OS_PASSWORD: "adminpassword"
    OS_AUTH_URL: "http://10.0.0.30:5000/v3"
    OS_IDENTITY_API_VERSION: "3"
    OS_IMAGE_API_VERSION: "2"
