all:
  children:
    openstack_controller:
      hosts:
        10.85.103.252:
    openstack_compute:
      hosts:
        10.85.103.242:
        10.85.103.252:
    openstack_volume:
      hosts:
        10.85.103.242:
        10.85.103.252:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_t123
    ansible_ssh_user: admin 
    ansible_become: true
    openstack_release: xena
    proxy_env:
      http_proxy: http://12.34.56.78:80/
      https_proxy: http://12.34.56.78:80/
      no_proxy: 127.0.0.1
    openstack_env:
      OS_PROJECT_DOMAIN_NAME: "default"
      OS_USER_DOMAIN_NAME: "default"
      OS_PROJECT_NAME: "admin"
      OS_USERNAME: "admin"
      OS_PASSWORD: "adminpassword"
      OS_AUTH_URL: "http://127.0.0.1:5000/v3"
      OS_IDENTITY_API_VERSION: "3"
      OS_IMAGE_API_VERSION: "2"
    dns_nameserver: 8.8.8.8
    provider_interface: enp2s0f0
    neutron_tenant_type: vxlan
