- name: 
  set_fact:
    my_ip: "{{ ansible_default_ipv4.address }}"

- name: KVM
  block:
    - name: KVM - Install
      package:
        name: "{{ libvirt_kvm_packages }}"

    - name: KVM - Enable and start libvirtd
      service:
        name: libvirtd
        enabled: yes
        state: started

- name: Install and Configure Chrony
  package:
    name: chrony
    state: present

- name: Nova
  block:
    - name: Nova - Install
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      dnf:
        name: openstack-nova
        enablerepo: centos-openstack-{{ openstack_release }},powertools,epel
        state: latest

    - name: Nova - Install
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      package:
        name: nova-compute
        state: latest

    - name: Nova - Copy nova.conf
      template:
        backup: yes
        src:  "nova.conf"
        dest: /etc/nova/
        owner: root
        group: nova 
        mode: 0640

    - name: Nova - Copy nova-compute.conf
      template:
        backup: yes
        src:  "nova-compute.conf"
        dest: /etc/nova/
        owner: root
        group: nova 
        mode: 0640

    - name: Nova - enable & start compute service
      service:
        name: "{{ nova_compute_service }}"
        enabled: yes
        state: restarted
